name: Deploy Frontend to S3 + CloudFront

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/Checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/Configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIASMXY4QQLNUNU7LXI
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Sync frontend to S3
        run: |
          aws s3 sync ./frontend s3://${{ secrets.S3_BUCKET }} --delete
      - name: Invalidate CloudFront cache
        if: env.CLOUDFRONT_DIST_ID != ''
        env: 
          CLOUDFRONT_DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id $CLOUDFRONT_DIST_ID \
            --path "/*"
